# build environment
FROM node:14-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --silent
# RUN npm install @vue/cli -g
COPY . /app
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY ./gzip.conf /etc/nginx/conf.d/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]