version: "3"
services:
  web:
    image: docker-hub.siap.id/lms-sv/web-devel:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - /app/node_modules
    ports:
      - "8080:8080"
