version: "3.5"

services:
  web:
    image: docker-hub.siap.id/lms-sv/web-demo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    ports:
      - 8082:80
