version: "3.5"

services:
  web:
    image: docker-hub.dev.siap.id/siap-belajar/web-devel:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    ports:
      - 5055:80
